# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site title and description
title: DeskThemesite
description: Knowledge base Jekyll theme.

# Site subpath, e.g. /blog
baseurl: ''

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink: /:title/

# Timezone for timestamp
timezone: Europe/Dublin

# Site base hostname & protocol, e.g. http://example.com
url: 'https://robbertl.github.io'

# Site logo, dark and light depending on page hero text setting dark/light
brand:
  text: DeskThemesite # e.g. logo.png, upload logo image file to /assets/posts/ folder

# Author settings, displayed on about page
author:
  name: John Smith
  email:
  website: https://www.desktheme.ie
  facebook: https://www.facebook.com
  flickr:
  dribbble:
  github:
  googleplus:
  instagram: 
  linkedin: https://www.linkedin.com
  pinterest:
  twitter: https://www.twitter.com
  vimeo: 
  youtube:

# Social share buttons
twitter_username: somename
github_username: somename

# Default footer image settings
footer:
  copyright: <a href="https://desktheme.ie">DeskTheme</a> Ireland | Design <a href="https://unbound.studio/">Unbound Studio</a>

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
  shortname: # 7865

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Google maps API key, get your key here: https://developers.google.com/maps/documentation/javascript/get-api-key
google_maps_api_key:

# Path to post content assets directory i.e post images, pdfs etc
post_assets: /assets/posts/

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style: compressed

collections:
  faqs:
    output: false

sitemap:
  lastmod: 2023-01-30
  priority: 0.7
  changefreq: 'weekly'
  exclude: 'yes'
